### ISSUE TITLE
Error when using Xcode Cloud

### ISSUE THREAD

**Issue by hactar** [lukepistrol/SwiftLintPlugin#17]
This is a reopen of https://github.com/lukepistrol/SwiftLintPlugin/issues/15

I've just run into the same issue, and moving over to the official plug in resolved the issue, but just adding the spm takes ages now as the swiftlint repo is a giant...

Looks like your version appears to be not including a specific plugin fix which involves disabling caching while running in CI mode - see this comment by a disgruntled developer 😅

https://github.com/realm/SwiftLint/issues/5448#issuecomment-1919842806

**Comment by lukepistrol** [comment]
Hey @hactar :) Thanks for your suggestion. I implemented the changes necessary but since I currently have no project setup with Xcode Cloud could I ask you to test it with the [fix/#17-xcode-cloud](https://github.com/lukepistrol/SwiftLintPlugin/tree/fix/%2317-xcode-cloud-error) branch and report back if you encountered any errors?

**Comment by hactar** [comment]
@lukepistrol I can confirm that this branch now works correctly on Xcode Cloud. Thanks!

**Comment by lukepistrol** [comment]
Perfect! I'll merge it into `main` for now and it will be available in the next release once SwiftLint releases a new version.
